package date2021.oldpackage;//CREATE TABLE `b2c_workers` (
//        `id` int(11) NOT NULL AUTO_INCREMENT,
//        `mobile` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '手机号',
//        `nickname` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '用户昵称/真实姓名',
//        `password` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '用户密码',
//        `salt` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '密码盐',
//        `p_id` int(11) NOT NULL DEFAULT '0' COMMENT '邀请人ID',
//        `level` tinyint(10) NOT NULL DEFAULT '0' COMMENT '用户等级',
//        `gender` tinyint(4) NOT NULL DEFAULT '1' COMMENT '性别1男2女',
//        `avatar` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '头像',
//        `invite_code` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '邀请码',
//        `reg_type` tinyint(10) NOT NULL DEFAULT '1' COMMENT '注册方式1正常注册2微信注册',
//        `flag` varchar(30) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '标记:1=打标工人',
//        `reg_channel` varchar(30) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '下载渠道',
//        `reg_at` datetime DEFAULT NULL COMMENT '成功入驻时间',
//        `has_pwd` tinyint(10) NOT NULL DEFAULT '0' COMMENT '是否设置登录密码0否1是',
//        `successions` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '连续登陆天数',
//        `maxsuccessions` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '最大登陆天数',
//        `prevtime` int(10) DEFAULT NULL COMMENT '上次登录时间',
//        `logintime` int(10) DEFAULT NULL COMMENT '登录时间',
//        `loginip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '登陆IP',
//        `loginfailure` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '失败次数',
//        `has_info` tinyint(255) NOT NULL DEFAULT '0' COMMENT '0无1有',
//        `status` varchar(30) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '账号状态normal:正常hidden:冻结locked:拉黑',
//        `has_punishment` tinyint(4) NOT NULL DEFAULT '2' COMMENT '是否有罚单未处理: 1=有, 2=没有',
//        `register_step` tinyint(4) NOT NULL DEFAULT '1' COMMENT '注册步骤 1 完善资料  2 完成服务承诺 3 实名认证 4考试5入驻成功',
//        `has_auth` tinyint(4) NOT NULL DEFAULT '2' COMMENT '是否认证1已认证2未认证',
//        `has_deposit` tinyint(4) NOT NULL DEFAULT '2' COMMENT '是否缴纳保证金1已缴纳2未缴纳',
//        `has_exam` tinyint(4) NOT NULL DEFAULT '2' COMMENT '考试状态1已通过入驻考试2未看资料3已看未考试4=通过主类目考试',
//        `created_at` timestamp NULL DEFAULT NULL COMMENT '加入时间',
//        `updated_at` timestamp NULL DEFAULT NULL,
//        `after_sale_remind_time` datetime DEFAULT NULL COMMENT '售后工单app弹窗提醒时间',
//        PRIMARY KEY (`id`),
//        UNIQUE KEY `mobile` (`mobile`),
//        KEY `mobile_key` USING BTREE (`mobile`)
//        ) ENGINE = InnoDB AUTO_INCREMENT = 170 DEFAULT CHARSET = utf8 DEFAULT COLLATE = utf8_bin COMMENT '工人师傅表'
//
//
//        CREATE TABLE `b2c_worker_extends` (
//        `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
//        `worker_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '师傅ID',
//        `ser_area_im` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '重点服务区域行政编码，最多1个',
//        `ser_area_pr` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '优先服务区域行政编码，最多2个',
//        `ser_area_no` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '普通服务区域行政编码，最多一个地级市的所有',
//        `ser_type` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '服务类型',
//        `ser_class_im` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '主要服务类目',
//        `ser_class_se` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '副服务类目，最多2个',
//        `ser_class_ho` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '意愿服务类目, 可多选',
//        `pass_class_se` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '考试通过的副类目',
//        `fixed_price_time` int(5) UNSIGNED DEFAULT NULL COMMENT '一口价可接单量',
//        `offer_time` int(5) UNSIGNED DEFAULT NULL COMMENT '报价可接单量',
//        `permanent_code` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '常驻地区坐标',
//        `permanent` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '常驻地址详情',
//        `coordinate` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '经纬度',
//        `crash_person_mobile` varchar(11) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '紧急联系人',
//        `aliauth_fail_count` int(10) NOT NULL DEFAULT '0' COMMENT '阿里实人认证错误次数',
//        `real_name` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '真实姓名',
//        `id_number` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '身份证号',
//        `id_front` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '身份证正面照',
//        `id_back` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '身份证背面',
//        `face_img` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '人面照',
//        `id_end_data` varchar(20) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '身份证有效期',
//        `service_score` tinyint(4) UNSIGNED NOT NULL DEFAULT '100' COMMENT '服务质量分，满分100',
//        `epi_score` decimal(10, 2) UNSIGNED NOT NULL DEFAULT '5.00' COMMENT '综合评分，满分5.00',
//        `acceptance` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '服务承诺',
//        `self_desc` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '自我介绍',
//        `admin_id` int(11) NOT NULL DEFAULT '0' COMMENT '操作者ID',
//        `admin_at` datetime DEFAULT NULL COMMENT '认证时间',
//        `jzb_deal` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否同意见证宝协议',
//        `created_at` timestamp NULL DEFAULT NULL,
//        `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
//        `ser_area_class_flag` varchar(45) COLLATE utf8_bin DEFAULT '0,0,0,0,0',
//        `title_ids` varchar(255) COLLATE utf8_bin DEFAULT '',
//        `grade_id` int(11) DEFAULT '0',
//        `server_skill_ids` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '服务技能多个用,隔开',
//        PRIMARY KEY (`id`),
//        KEY `worker_id` USING BTREE (`worker_id`),
//        KEY `idx_ser_area_im` USING BTREE (`ser_area_im`) COMMENT '主要服务区域',
//        KEY `idx_id_number` USING BTREE (`id_number`)
//        ) ENGINE = InnoDB AUTO_INCREMENT = 228 DEFAULT CHARSET = utf8 DEFAULT COLLATE = utf8_bin COMMENT '工人师傅信息表'  ;